---
- name: Deploy kitty config
  ansible.builtin.copy:
    src: kitty/kitty/
    dest: "{{ home }}/.config/kitty/"

- name: Deploy kitty zsh integration fragment
  ansible.builtin.copy:
    src: kitty/conf.d/
    dest: "{{ home }}/.config/zsh/conf.d/"
