---
- name: Deploy Chrome web app desktop entries
  ansible.builtin.copy:
    src: apps/web-apps/applications/
    dest: "{{ home }}/.local/share/applications/"
  notify:
    - Update desktop database
    - Update icon cache

- name: Deploy Chrome web app icons
  ansible.builtin.copy:
    src: apps/web-apps/icons/
    dest: "{{ home }}/.local/share/icons/"
  notify:
    - Update desktop database
    - Update icon cache
