---
- name: Install oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ home }}/.oh-my-zsh"
    depth: 1
    update: false

- name: Deploy zshrc skeleton
  ansible.builtin.copy:
    src: apps/zsh/zshrc
    dest: "{{ home }}/.zshrc"

- name: Deploy zsh conf.d fragments
  ansible.builtin.copy:
    src: apps/zsh/conf.d/
    dest: "{{ home }}/.config/zsh/conf.d/"

- name: Deploy zsh syntax highlighting theme
  ansible.builtin.copy:
    src: apps/zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh
    dest: "{{ home }}/.local/share/catppuccin_mocha-zsh-syntax-highlighting.zsh"
