# mpv config

# catppuccin mocha blue theme
include=~~/catppuccin-mocha-blue.conf

profile=high-quality
vo=gpu
hwdec=auto-safe
save-position-on-quit=yes
keep-open=yes
screenshot-format=png
screenshot-directory=~/Pictures/mpv
sub-auto=fuzzy
slang=chi,zh,eng
alang=jpn,chi,zh,eng
osd-font=CaskaydiaCove NF

# mpv-mpris (extra repo), auto-loaded after install
script=/usr/lib/mpv-mpris.so
