# satty 截图标注工具配置
[general]
# 退出时复制到剪贴板
copy-command = "wl-copy"
# 初始工具
initial-tool = "brush"
output-filename = "~/Pictures/satty-%Y%m%d-%H%M%S.png"
save-after-copy = true

[font]
family = "Noto Sans"
style = "Regular"
