# kitty 配置
# 文档: https://sw.kovidgoyal.net/kitty/conf.html

# catppuccin mocha 主题（来自 kitty-themes，本地副本）
include Catppuccin-Mocha.conf

# Shell integration is sourced and configured manually
shell_integration no-rc

adjust_line_height 120%
background_opacity 0.98
enable_audio_bell no
font_family CaskaydiaCove NFM
font_size 14
scrollback_lines 65535
window_padding_width 6
