# mpv 配置

# catppuccin mocha blue 主题
include=~~/catppuccin-mocha-blue.conf

profile=high-quality
vo=gpu
hwdec=auto-safe
save-position-on-quit=yes
keep-open=yes
screenshot-format=png
screenshot-directory=~/Pictures/mpv
sub-auto=fuzzy
slang=chi,zh,eng
alang=jpn,chi,zh,eng
osd-font=CaskaydiaCove NF

# mpv-mpris（extra 仓库），安装后自动加载
script=/usr/lib/mpv-mpris.so
