# satty screenshot annotation tool config
[general]
# copy to clipboard on exit
copy-command = "wl-copy"
# initial tool
initial-tool = "brush"
output-filename = "~/Pictures/satty-%Y%m%d-%H%M%S.png"
save-after-copy = true

[font]
family = "Noto Sans"
style = "Regular"
